apiVersion: v2
name: demo-crm
version: 1.0.0
dependencies:
  - name: mongodb
    version: 13.1.7
    repository: https://charts.bitnami.com/bitnami
  - name: rabbitmq
    version: 11.0.4
    repository: https://charts.bitnami.com/bitnami
  - name: cert-manager
    version: 1.0.0

