apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-crm-test
  namespace: default
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: charts/demo-crm
    repoURL: git@github.com:adam-stegienko/argo-app.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true