apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-data-remover
  namespace: default
spec:
  schedule: '@daily'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-data-remover
            image: mongo
            env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: MONGODB_ROOT_USER
            - name: PWD
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: MONGODB_ROOT_PASSWORD
            command: ["/bin/sh","-c"]
            args:
            - mongosh --host "news-getter-mongodb-0.news-getter-mongodb-headless" --username "$(USER)" -p "$(PWD)" --eval "db.clients.deleteMany( {} )"
          restartPolicy: OnFailure